export const ADD_ARTICLE = "ADD_ARTICLE";
export const SET_FABRICANTE_COMPRA = "SET_FABRICANTE_COMPRA";


//FETCH CATEGORIES
export const FETCH_CATEGORIAS_PENDING = 'FETCH_CATEGORIAS_PENDING';
export const FETCH_CATEGORIAS_SUCCESS = 'FETCH_CATEGORIAS_SUCCESS';
export const FETCH_CATEGORIAS_ERROR = 'FETCH_CATEGORIAS_ERROR';